version: "3.7"
services:

  postgres:
    image: postgres:13.0-alpine
    environment:
      # POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      envoymesh:
        aliases:
          - postgres

  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    volumes:
      - ./example_envoy.yaml:/etc/envoy.yaml
    networks:
      envoymesh:
    ports:
      - "9901:9901"
      - "5432:5432"
    depends_on: 
      - postgres

networks:
  envoymesh: {}
